name: siameseQAT
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - mlflow==1.18.0
    - requests==2.25.1
    - googledrivedownloader==0.4
    - papermill==2.3.3
    - click==8.0.1
    - pytest==3.5.1
    - scikit-learn==0.24.2
    - pandas==1.2.5
    - networkx==2.1
    - tqdm==4.32.2
    - keras-bert==0.81.1
    - keras==2.3.0
    - tensorflow==2.2.0
    - numpy==1.19.2
    - matplotlib==3.4.2
    - annoy==1.15.2
variables:
  PYTHONPATH: .
  TF_KERAS: 1